apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    app: vault
spec:
  type: {{ .Values.vault.serviceType }}
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault
